# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tawny Sit
tagline:          'Astronomy Graduate Student'
description:      'PhD Candidate in Astronomy at <a href="https://astronomy.osu.edu/">The Ohio State University</a>.'
url:              https://tawnysit.github.io
baseurl:          https://tawnysit.github.io/

author:
  name:           'Tawny Sit'
  email:          sit.6@osu.edu

# Custom vars
orcid_username:   0000-0001-8208-9755
github:
  repo:           https://github.com/tawnysit/tawnysit.github.io
version:          2025/02/03
github_username:  tawnysit
