# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tawny Sit
tagline:          'Astronomy Graduate Student'
description:      'Graduate Student in Astronomy at <a href="https://astronomy.osu.edu/">The Ohio State University</a>.'
url:              http://tawnysit.github.io
baseurl:          /

author:
  name:           'Tawny Sit'
  email:          sit.6@osu.edu

paginate:         1
paginate_path:    "page:num"

# Custom vars
emailme:          mailto:sit.6@osu.edu
orcid_username:   0000-0001-8208-9755
github:
  repo:           https://github.com/tawnysit/tawnysit.github.io
version:          2024/03/14
